package com.github.shop.generate.mapper;

import com.github.shop.generate.OrderGoodsMapping;
import com.github.shop.generate.OrderGoodsMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface OrderGoodsMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    long countByExample(OrderGoodsMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    int deleteByExample(OrderGoodsMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    int insert(OrderGoodsMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    int insertSelective(OrderGoodsMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    List<OrderGoodsMapping> selectByExample(OrderGoodsMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    OrderGoodsMapping selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") OrderGoodsMapping record, @Param("example") OrderGoodsMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    int updateByExample(@Param("record") OrderGoodsMapping record, @Param("example") OrderGoodsMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    int updateByPrimaryKeySelective(OrderGoodsMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    int updateByPrimaryKey(OrderGoodsMapping record);
}