package com.github.shop.generate;

import java.time.LocalDate;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.id
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.shop_id
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.name
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.description
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.img_url
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.price
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.stock
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.status
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.create_time
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private LocalDate createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.update_time
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private LocalDate updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.details
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.id
     *
     * @return the value of shop_goods.id
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.id
     *
     * @param id the value for shop_goods.id
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.shop_id
     *
     * @return the value of shop_goods.shop_id
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.shop_id
     *
     * @param shopId the value for shop_goods.shop_id
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.name
     *
     * @return the value of shop_goods.name
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.name
     *
     * @param name the value for shop_goods.name
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.description
     *
     * @return the value of shop_goods.description
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.description
     *
     * @param description the value for shop_goods.description
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.img_url
     *
     * @return the value of shop_goods.img_url
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.img_url
     *
     * @param imgUrl the value for shop_goods.img_url
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.price
     *
     * @return the value of shop_goods.price
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.price
     *
     * @param price the value for shop_goods.price
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.stock
     *
     * @return the value of shop_goods.stock
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.stock
     *
     * @param stock the value for shop_goods.stock
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.status
     *
     * @return the value of shop_goods.status
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.status
     *
     * @param status the value for shop_goods.status
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.create_time
     *
     * @return the value of shop_goods.create_time
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public LocalDate getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.create_time
     *
     * @param createTime the value for shop_goods.create_time
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setCreateTime(LocalDate createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.update_time
     *
     * @return the value of shop_goods.update_time
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public LocalDate getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.update_time
     *
     * @param updateTime the value for shop_goods.update_time
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setUpdateTime(LocalDate updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.details
     *
     * @return the value of shop_goods.details
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.details
     *
     * @param details the value for shop_goods.details
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }
}