package com.github.shop.generate;

public class OrderGoodsMapping {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_goods.id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_goods.goods_id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_goods.order_id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_goods.number
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private Long number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_goods.id
     *
     * @return the value of shop_order_goods.id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_goods.id
     *
     * @param id the value for shop_order_goods.id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_goods.goods_id
     *
     * @return the value of shop_order_goods.goods_id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_goods.goods_id
     *
     * @param goodsId the value for shop_order_goods.goods_id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_goods.order_id
     *
     * @return the value of shop_order_goods.order_id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_goods.order_id
     *
     * @param orderId the value for shop_order_goods.order_id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_goods.number
     *
     * @return the value of shop_order_goods.number
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public Long getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_goods.number
     *
     * @param number the value for shop_order_goods.number
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setNumber(Long number) {
        this.number = number;
    }
}