package com.github.shop.generate;

import java.time.LocalDate;

public class ShoppingCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_shopping_cart.id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_shopping_cart.user_id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_shopping_cart.goods_id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_shopping_cart.shop_id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_shopping_cart.number
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_shopping_cart.status
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_shopping_cart.create_time
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private LocalDate createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_shopping_cart.update_time
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private LocalDate updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_shopping_cart.id
     *
     * @return the value of shop_shopping_cart.id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_shopping_cart.id
     *
     * @param id the value for shop_shopping_cart.id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_shopping_cart.user_id
     *
     * @return the value of shop_shopping_cart.user_id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_shopping_cart.user_id
     *
     * @param userId the value for shop_shopping_cart.user_id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_shopping_cart.goods_id
     *
     * @return the value of shop_shopping_cart.goods_id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_shopping_cart.goods_id
     *
     * @param goodsId the value for shop_shopping_cart.goods_id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_shopping_cart.shop_id
     *
     * @return the value of shop_shopping_cart.shop_id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_shopping_cart.shop_id
     *
     * @param shopId the value for shop_shopping_cart.shop_id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_shopping_cart.number
     *
     * @return the value of shop_shopping_cart.number
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_shopping_cart.number
     *
     * @param number the value for shop_shopping_cart.number
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_shopping_cart.status
     *
     * @return the value of shop_shopping_cart.status
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_shopping_cart.status
     *
     * @param status the value for shop_shopping_cart.status
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_shopping_cart.create_time
     *
     * @return the value of shop_shopping_cart.create_time
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public LocalDate getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_shopping_cart.create_time
     *
     * @param createTime the value for shop_shopping_cart.create_time
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setCreateTime(LocalDate createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_shopping_cart.update_time
     *
     * @return the value of shop_shopping_cart.update_time
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public LocalDate getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_shopping_cart.update_time
     *
     * @param updateTime the value for shop_shopping_cart.update_time
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setUpdateTime(LocalDate updateTime) {
        this.updateTime = updateTime;
    }
}