package com.github.shop.generate;

import java.time.LocalDate;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_shop.id
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_shop.name
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_shop.description
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_shop.img_url
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_shop.owner_user_id
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private Long ownerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_shop.status
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_shop.create_time
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private LocalDate createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_shop.update_time
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    private LocalDate updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_shop.id
     *
     * @return the value of shop_shop.id
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_shop.id
     *
     * @param id the value for shop_shop.id
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_shop.name
     *
     * @return the value of shop_shop.name
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_shop.name
     *
     * @param name the value for shop_shop.name
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_shop.description
     *
     * @return the value of shop_shop.description
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_shop.description
     *
     * @param description the value for shop_shop.description
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_shop.img_url
     *
     * @return the value of shop_shop.img_url
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_shop.img_url
     *
     * @param imgUrl the value for shop_shop.img_url
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_shop.owner_user_id
     *
     * @return the value of shop_shop.owner_user_id
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public Long getOwnerUserId() {
        return ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_shop.owner_user_id
     *
     * @param ownerUserId the value for shop_shop.owner_user_id
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setOwnerUserId(Long ownerUserId) {
        this.ownerUserId = ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_shop.status
     *
     * @return the value of shop_shop.status
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_shop.status
     *
     * @param status the value for shop_shop.status
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_shop.create_time
     *
     * @return the value of shop_shop.create_time
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public LocalDate getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_shop.create_time
     *
     * @param createTime the value for shop_shop.create_time
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setCreateTime(LocalDate createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_shop.update_time
     *
     * @return the value of shop_shop.update_time
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public LocalDate getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_shop.update_time
     *
     * @param updateTime the value for shop_shop.update_time
     *
     * @mbg.generated Sun Jun 14 20:58:18 CST 2020
     */
    public void setUpdateTime(LocalDate updateTime) {
        this.updateTime = updateTime;
    }
}