package com.github.shop.generate;

import java.time.LocalDate;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.name
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.tel
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.avatar_url
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.address
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.create_time
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private LocalDate createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.update_time
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    private LocalDate updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.id
     *
     * @return the value of shop_user.id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.id
     *
     * @param id the value for shop_user.id
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.name
     *
     * @return the value of shop_user.name
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.name
     *
     * @param name the value for shop_user.name
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.tel
     *
     * @return the value of shop_user.tel
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.tel
     *
     * @param tel the value for shop_user.tel
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.avatar_url
     *
     * @return the value of shop_user.avatar_url
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.avatar_url
     *
     * @param avatarUrl the value for shop_user.avatar_url
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.address
     *
     * @return the value of shop_user.address
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.address
     *
     * @param address the value for shop_user.address
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.create_time
     *
     * @return the value of shop_user.create_time
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public LocalDate getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.create_time
     *
     * @param createTime the value for shop_user.create_time
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setCreateTime(LocalDate createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.update_time
     *
     * @return the value of shop_user.update_time
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public LocalDate getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.update_time
     *
     * @param updateTime the value for shop_user.update_time
     *
     * @mbg.generated Sun Jun 14 00:26:35 CST 2020
     */
    public void setUpdateTime(LocalDate updateTime) {
        this.updateTime = updateTime;
    }
}